# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: "Ubuntu-16.04"

steps:
  - task: Docker@2
    displayName: "Login to DockerHub"
    inputs:
      command: login
  - task: Docker@2
    displayName: "Build docker container"
    inputs:
      command: build
      repository: rinsuki/sea
      tags: latest
  - script: |
      docker run --name postgres -e POSTGRES_PASSWORD=onlyfortesting postgres:10-alpine
    displayName: "Run PostgreSQL"
  - script: |
      docker run --rm --link postgres:postgres -e DATABASE_URL="postgres://postgres:onlyfortesting@postgres/postgres" yarn test
    displayName: "Run yarn test"
  - task: Docker@2
    displayName: "Push to DockerHub"
    inputs:
      command: push
      repository: rinsuki/sea
      tags: latest
  - task: Docker@2
    displayName: "Log-out from DockerHub"
    inputs:
      command: logout
